/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CodeOfConductImport } from './routes/code-of-conduct'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CodeOfConductRoute = CodeOfConductImport.update({
  path: '/code-of-conduct',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/code-of-conduct'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/code-of-conduct'
  id: '__root__' | '/' | '/code-of-conduct'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeOfConductRoute: CodeOfConductRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/code-of-conduct"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/code-of-conduct": {
      "filePath": "code-of-conduct.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
